name: Conjur Integration Test (Manual)

on:
  push:
    branches:
      - master

jobs:
  run-with-conjur:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure Conjur CLI
        run: |
          echo "CONJUR_URL=https://192.168.112.129" >> $GITHUB_ENV
          echo "CONJUR_ACCOUNT=18kaio" >> $GITHUB_ENV
          echo "CONJUR_AUTHN_LOGIN=host/github-runner-policy/juice-shop-github-runner" >> $GITHUB_ENV
          echo "CONJUR_AUTHN_API_KEY=${{ secrets.CONJUR_API_KEY }}" >> $GITHUB_ENV

      - name: Login and get secret with Conjur CLI
        run: |
          conjur authn login
          SECRET=$(conjur variable get -i github-runner-policy/my-secret-folder)
          echo "O segredo foi buscado do Conjur com sucesso."
          echo "Valor do segredo: ${SECRET}"
