name: Conjur Integration Test

on:
  push:
    branches:
      - master

jobs:
  run-with-conjur:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get credentials from Conjur
        id: conjur_secrets
        uses: cyberark/conjur-action@v2.0.0
        with:
          url: https://192.168.112.129
          account: 18kaio
          host_id: ${{ secrets.CONJUR_HOST_ID }}
          api_key: ${{ secrets.CONJUR_API_KEY }}
          secrets: github-runner-policy/my-secret-folder

      - name: Use the secret
        run: |
          echo "O segredo foi buscado do Conjur com sucesso."
          echo "Valor do segredo: ${{ steps.conjur_secrets.outputs.github_runner_policy_my_secret_folder }}"
